package com.SmartBiz.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * SubscriptionPlan Entity - Defines the pricing/feature plans available for
 * businesses.
 *
 * Each subscription plan has:
 * - A plan name (e.g., "Basic", "Pro", "Enterprise")
 * - A price
 * - An AI token limit (how many AI tokens the business can use)
 * - A max users limit (how many admin users the business can have)
 *
 * Businesses subscribe to one of these plans (Businesses → SubscriptionPlan).
 * Admins can create and update these plans via the Admin API.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class SubscriptionPlan {

    // Primary key - unique identifier for each subscription plan
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long subscription_id;

    // Name of the plan (e.g., "Basic", "Pro", "Enterprise")
    private String plan_name;

    // Monthly/annual price of the subscription plan
    private double price;

    // Maximum number of AI tokens allowed under this plan
    private int ai_token_limit;

    // Maximum number of admin users allowed under this plan
    private int max_users;

    // Billing cycle (e.g., "Monthly", "Annual")
    private String billing_cycle;

    // Timestamp when the plan was created (stored as String)
    private String created_at;

    /**
     * Custom constructor - Creates a SubscriptionPlan without setting the ID.
     * Useful when creating a new plan (ID is auto-generated by the database).
     */
    public SubscriptionPlan(String plan_name, double price, int ai_token_limit, int max_users, String created_at) {
        this.plan_name = plan_name;
        this.price = price;
        this.ai_token_limit = ai_token_limit;
        this.max_users = max_users;
        this.created_at = created_at;
    }
}
